server:
  port: 8092

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8092
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
  application:
    name: rabbitMq
  zipkin:
    sender:
      type: rabbit  # 切换到rabbitmq
  sleuth:
    sampler:
      #应采样的请求的概率。 例如。 应该对1.0  -  100％的请求进行抽样。 精度仅为整数（即不支持0.1％的迹线）。
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: lbl
    password: 123456
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true

