eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8084
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/

spring:
  application:
    name: file

server:
  port: 8084