eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8081
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/

server:
  port: 8081

spring:
  application:
    name: zuul-zipkin
  zipkin:
    base-url: http://localhost:9411

zuul:
  routes:
    file:
      path: /file/*
      serviceId : server-file
