eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8092
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/

server:
  port: 8092

spring:
  application:
    name: note
