#配置mongodb参数
spring:
  application:
    name: mongodb
  data:
    mongodb:
      host: 172.30.0.218
      port: 27017
      database: mydb

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8093
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/

server:
  port: 8086

